# ====== DATABASE ======
spring.datasource.url=${URL_DB}
spring.datasource.username=${USERNAME_DB}
spring.datasource.password=${PASSWORD_DB}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.connection-init-sql=SET NAMES utf8mb4

# ====== JPA ======
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ====== LOGGING ======
logging.level.root=INFO
logging.file.name=logs/app-prod.log
logging.file.max-size=10MB
logging.file.max-history=14
